// Copyright 2024 tsuru authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package provider

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/tsuru/rpaas-operator/pkg/rpaas/client/autogenerated"
)

func TestFlattenScaleDown(t *testing.T) {
	tests := []struct {
		name           string
		scaleDownRead  autogenerated.ScaleDown
		scaleDownInput interface{}
		expected       interface{}
	}{
		{
			name:           "empty scale down returns nil",
			scaleDownRead:  autogenerated.ScaleDown{},
			scaleDownInput: nil,
			expected:       nil,
		},
		{
			name: "no input parameters, only set values are included",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue:         autogenerated.PtrInt32(10),
				StabilizationWindowSeconds: autogenerated.PtrInt32(300),
			},
			scaleDownInput: nil,
			expected: []map[string]interface{}{{
				"percentage":           10,
				"stabilization_window": 300,
			}},
		},
		{
			name: "with input parameters, preserve user's intent",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue:         autogenerated.PtrInt32(10),
				StabilizationWindowSeconds: autogenerated.PtrInt32(300),
				UnitsPolicyValue:           autogenerated.PtrInt32(5),
			},
			scaleDownInput: []interface{}{
				map[string]interface{}{
					"percentage": 15,
					"units":      3,
				},
			},
			expected: []map[string]interface{}{{
				"percentage": 10,
				"units":      5,
			}},
		},
		{
			name: "user specified only units",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue:         autogenerated.PtrInt32(10),
				StabilizationWindowSeconds: autogenerated.PtrInt32(300),
				UnitsPolicyValue:           autogenerated.PtrInt32(3),
			},
			scaleDownInput: []interface{}{
				map[string]interface{}{
					"units": 5,
				},
			},
			expected: []map[string]interface{}{{
				"units": 3,
			}},
		},
		{
			name: "user specified stabilization_window but API doesn't return it",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue: autogenerated.PtrInt32(10),
			},
			scaleDownInput: []interface{}{
				map[string]interface{}{
					"percentage":           10,
					"stabilization_window": 300,
				},
			},
			expected: []map[string]interface{}{{
				"percentage": 10,
			}},
		},
		{
			name: "all fields specified and returned",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue:         autogenerated.PtrInt32(15),
				StabilizationWindowSeconds: autogenerated.PtrInt32(600),
				UnitsPolicyValue:           autogenerated.PtrInt32(2),
			},
			scaleDownInput: []interface{}{
				map[string]interface{}{
					"percentage":           10,
					"stabilization_window": 300,
					"units":                3,
				},
			},
			expected: []map[string]interface{}{{
				"percentage":           15,
				"stabilization_window": 600,
				"units":                2,
			}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := flattenScaleDown(tt.scaleDownRead, tt.scaleDownInput)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestFlattenScaleDownNoInput(t *testing.T) {
	tests := []struct {
		name          string
		scaleDownRead autogenerated.ScaleDown
		expected      interface{}
	}{
		{
			name:          "empty scale down",
			scaleDownRead: autogenerated.ScaleDown{},
			expected:      nil,
		},
		{
			name: "only percentage set",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue: autogenerated.PtrInt32(20),
			},
			expected: []map[string]interface{}{{
				"percentage": 20,
			}},
		},
		{
			name: "all fields set",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue:         autogenerated.PtrInt32(25),
				StabilizationWindowSeconds: autogenerated.PtrInt32(450),
				UnitsPolicyValue:           autogenerated.PtrInt32(7),
			},
			expected: []map[string]interface{}{{
				"percentage":           25,
				"stabilization_window": 450,
				"units":                7,
			}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := flattenScaleDownNoInput(tt.scaleDownRead)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestFlattenScaleDownWithInput(t *testing.T) {
	tests := []struct {
		name          string
		scaleDownRead autogenerated.ScaleDown
		proposedList  []map[string]interface{}
		expected      interface{}
	}{
		{
			name:          "empty proposed list",
			scaleDownRead: autogenerated.ScaleDown{},
			proposedList:  []map[string]interface{}{},
			expected:      nil,
		},
		{
			name: "user specified percentage only",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue:         autogenerated.PtrInt32(15),
				StabilizationWindowSeconds: autogenerated.PtrInt32(300),
				UnitsPolicyValue:           autogenerated.PtrInt32(5),
			},
			proposedList: []map[string]interface{}{{
				"percentage": 10,
			}},
			expected: []map[string]interface{}{{
				"percentage": 15,
			}},
		},
		{
			name: "user specified all fields but API only returns some",
			scaleDownRead: autogenerated.ScaleDown{
				PercentPolicyValue: autogenerated.PtrInt32(10),
			},
			proposedList: []map[string]interface{}{{
				"percentage":           10,
				"stabilization_window": 300,
				"units":                3,
			}},
			expected: []map[string]interface{}{{
				"percentage": 10,
			}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := flattenScaleDownWithInput(tt.scaleDownRead, tt.proposedList)
			assert.Equal(t, tt.expected, result)
		})
	}
}
